### ISSUE TITLE
uploading videos

### ISSUE THREAD

**Issue by theonester** [Assasans/found-footage#23] opened 2024-05-12 18:21 UTC
@Assasans Hi. Is there any way to turn off my videos uploading? Can i be shure that my videos are not uploading on the server if i configured "0" for "DeathUploadChance" and "PassUploadChance"?

**Comment by Assasans** [comment] 2024-05-13 17:47
Fixed in f050729, regression fixed in 08c55ea. Available at v0.4.1.

v0.3.1 and earlier: random can return `0`, so the video would be uploaded, but the chances are very small.
Since v0.4.1 there is a check if chance is set to `0`, so the video will never be uploaded.

**Closed by Assasans** 2024-05-13 17:47 UTC
