### ISSUE TITLE
The video is just stop

### ISSUE THREAD

**Issue by koteiyt** [Assasans/found-footage#11] opened 2024-04-14 11:56 UTC
while playing the video, it stops abruptly, I attach the logs
[LogOutput.log](https://github.com/Assasans/found-footage/files/14970567/LogOutput.log)

**Comment by koteiyt** [comment] 2024-04-14 12:07
host is my friend

**Comment by koteiyt** [comment] 2024-04-14 14:05
?

**Comment by Assasans** [comment] 2024-04-14 14:31
The log seems normal, there are no exceptions during video playback. I can't test this right now, try temporarily disabling all other mods and see if the bug persists, if so, upload the log. Same problem in #8.

**Comment by koteiyt** [comment] 2024-04-14 15:03
okay,i try

**Comment by koteiyt** [comment] 2024-04-14 15:08
And also, my friend was fine, I was playing with him

**Comment by koteiyt** [comment] 2024-04-14 15:11
When I'm alone and without mods, everything works

**Comment by koteiyt** [comment] 2024-04-14 15:12
i'l try with mods

**Comment by koteiyt** [comment] 2024-04-14 15:21
it works with mods too lol

**Comment by koteiyt** [comment] 2024-04-14 15:21
i try later with my friend

**Comment by koteiyt** [comment] 2024-04-14 17:37
when i play with friend it frezzes

**Comment by Assasans** [comment] 2024-04-17 10:48
Should be fixed in v0.2.2.

**Comment by Assasans** [comment] 2024-04-26 06:54
Closed due to inactivity, please reopen if the issue is not resolved.

**Closed by Assasans** 2024-04-26 06:54 UTC
