### ISSUE TITLE
Video download failure

### ISSUE THREAD

**Issue by FireFlower45YT** [Assasans/found-footage#14] opened 2024-04-21 17:16 UTC
I can put the lost camera in the extractor, and it gives a DVD, but everytime I put it in the TV, it doesnt play, and it says it cant find the file path, everytime.

**Comment by FireFlower45YT** [comment] 2024-04-21 17:39
Ok, so from what I've seen, they extract fine, and the whole video is in the files, but it saves as output.webm, not fullRecording.webm

**Comment by Assasans** [comment] 2024-04-21 18:14
`output.webm` should be copied to `fullRecording.webm' during the extract step. I saw this problem in someone's stream on YouTube. Maybe some mod is conflicting, can you upload a log when error occurs?

**Comment by FireFlower45YT** [comment] 2024-04-21 20:39
![image](https://github.com/Assasans/found-footage/assets/128944336/2a8ee767-fa34-46d5-a1f1-8eedf8962dea)

**Comment by Assasans** [comment] 2024-04-28 09:02
Do you have `MoreCameras` mod installed? I checked its source and it seems to do strange things with recordings during extraction. I'll try to fix this in the next release.

**Comment by Assasans** [comment] 2024-04-30 11:07
Should be fixed in v0.3.1.

**Comment by Bloqqy** [comment] 2024-04-30 21:15
Hey, I just updated Found Footage from Thunderstore and now I am unable to look the thing will say "Unable to get video path" i do not know if its because of that one mod that will allow me to save my recordings to other folders instead of desktop or sumth 
![Screenshot 2024-04-30 154520](https://github.com/Assasans/found-footage/assets/100400567/da823651-5e9d-4d5e-812d-bb335e471c6e)
![Screenshot 2024-04-30 154551](https://github.com/Assasans/found-footage/assets/100400567/070bcb10-28f8-42d1-b40f-aea1c3cc0d4c)

**Comment by Assasans** [comment] 2024-05-13 17:48
Closed due to inactivity, please reopen if the issue is not resolved.

**Closed by Assasans** 2024-05-13 17:48 UTC
